#!/bin/bash

# This script will install the required software packages on the system.

# Load packages from package-list file
packages=$(cat ./package-list)

# Construct the install command with system update
install="pacman -S --noconfirm"

# Append each package to the install command
for package in ${packages[@]}; do
	install+=" ${packages[@]}"
done

# Execute the install command
echo "Updating system package list and installing packages..."
$install
echo "All packages are installed successfully."
